/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.vizesonrasi_1;

import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author TA
 */
public class componentJOptionPane_1 extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(componentJOptionPane_1.class.getName());

    /**
     * Creates new form componentJOptionPane_1
     */
    public componentJOptionPane_1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Mesaj 1");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("Mesaj 2");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jButton3.setText("Mesaj 3");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jButton4.setText("Mesaj 4");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        jButton5.setText("Mesaj 5");
        jButton5.addActionListener(this::jButton5ActionPerformed);

        jButton6.setText("Mesaj 6");
        jButton6.addActionListener(this::jButton6ActionPerformed);

        jButton7.setText("Veri Al");
        jButton7.addActionListener(this::jButton7ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6)
                    .addComponent(jButton5)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton3)
                                .addComponent(jButton2)
                                .addComponent(jButton1)))
                        .addGap(91, 91, 91)
                        .addComponent(jButton7)))
                .addContainerGap(141, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton7))
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addGap(18, 18, 18)
                .addComponent(jButton6)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //import javax.swing.JOptionPane;
        JOptionPane.showMessageDialog(null, "İşlem başarılı");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        JOptionPane.showMessageDialog(
                null,
                "İşlem başarılı",
                "Bilgi",
                JOptionPane.INFORMATION_MESSAGE
        );
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(
                jButton1,
                "İşlem başarılı",
                "Bilgi",
                JOptionPane.INFORMATION_MESSAGE
        );
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int secim = JOptionPane.showConfirmDialog(
                this,
                "İşlem devam etsin mi?",
                "Onay",
                JOptionPane.YES_NO_OPTION
        );

        // secim değerleri:
        // 0 = YES
        // 1 = NO
        // -1 = X (kapatma)
        if (secim == JOptionPane.YES_OPTION) {
            // EVET seçildi
            JOptionPane.showMessageDialog(this, "İşlem devam ediyor");
        } else if (secim == JOptionPane.NO_OPTION) {
            // HAYIR seçildi
            JOptionPane.showMessageDialog(this, "İşlem iptal edildi");
        } else {
            // pencere kapatıldı
            JOptionPane.showMessageDialog(this, "Kullanıcı kapattı");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        int secim = JOptionPane.showOptionDialog(
                this,
                "İşlem başarılı",
                "Durum",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.INFORMATION_MESSAGE,
                null,
                new String[]{"Tamam", "-Detay-"},
                "Tamam"
        );

        // secim değeri açıklaması:
        // 0 → "Tamam" butonuna basıldı
        // 1 → "Detay" butonuna basıldı
        // -1 → kullanıcı pencereyi X ile kapattı (hiç seçim yapmadı)
        if (secim == 0) {
            // kullanıcı "Tamam" dedi
            JOptionPane.showMessageDialog(this, "Ana ekrana dönülüyor");
        } else if (secim == 1) {
            // kullanıcı "Detay" dedi
            JOptionPane.showMessageDialog(this, "Detay ekranı açılacak");
        } else if (secim == -1) {
            // kullanıcı dialogu kapattı (ESC veya X)
            JOptionPane.showMessageDialog(this, "İşlem iptal edildi");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        //import javax.swing.Icon;
        //import javax.swing.ImageIcon;
        //YOLU DEĞİŞTİR
        Icon icon = new ImageIcon("D:\\Belgeler\\NetBeansProjects\\vizeSonrasi_1\\src\\main\\java\\com\\mycompany\\vizesonrasi_1\\icon_1.png");
        int secim = JOptionPane.showOptionDialog(
                this,
                "İşlem başarılı",
                "Durum",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.INFORMATION_MESSAGE,
                icon,
                new String[]{"Tamam", "Detay", "Yeniden Dene", "İptal"},
                "Tamam"
        );

        //  secim değeri açıklaması:
        //  0 = Tamam
        //  1 = Detay
        //  2 = Yeniden Dene
        //  3 = İptal
        // -1 → kullanıcı pencereyi X ile kapattı (hiç seçim yapmadı)
        if (secim == 0) {
            // kullanıcı "Tamam" dedi
            JOptionPane.showMessageDialog(this, "Ana ekrana dönülüyor");
        } else if (secim == 1) {
            // kullanıcı "Detay" dedi
            JOptionPane.showMessageDialog(this, "Detay ekranı açılacak");
        } else if (secim == -1) {
            // kullanıcı dialogu kapattı (ESC veya X)
            JOptionPane.showMessageDialog(this, "İşlem iptal edildi");
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        String ad = JOptionPane.showInputDialog("Adınızı girin:");
        this.setTitle(ad);
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new componentJOptionPane_1().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    // End of variables declaration//GEN-END:variables
}
