/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.hafta5ogretim2;

import java.util.List;
import java.util.Random;
import javax.swing.DefaultListModel;

/**
 *
 * @author TA
 */
public class NewJFrame1 extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(NewJFrame1.class.getName());
    DefaultListModel<String> model1 = new DefaultListModel<>();
    DefaultListModel<String> model2 = new DefaultListModel<>();

    /**
     * Creates new form NewJFrame1
     */
    public NewJFrame1() {
        initComponents();

        jList1.setModel(model1);
        jList2.setModel(model2);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        btnSagAktarHepsi = new javax.swing.JButton();
        btnEkle = new javax.swing.JButton();
        btnSagAktarSecili1 = new javax.swing.JButton();
        btnSagAktarSecili2 = new javax.swing.JButton();
        btnSagAktarSecili3 = new javax.swing.JButton();
        btnSagAktarSecili4 = new javax.swing.JButton();
        btnSagAktarSecili5 = new javax.swing.JButton();
        btnSolAktarSecili = new javax.swing.JButton();
        btnSolAktarHepsi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList2);

        btnSagAktarHepsi.setText(">>");
        btnSagAktarHepsi.addActionListener(this::btnSagAktarHepsiActionPerformed);

        btnEkle.setText("Ekle");
        btnEkle.addActionListener(this::btnEkleActionPerformed);

        btnSagAktarSecili1.setText(">");
        btnSagAktarSecili1.addActionListener(this::btnSagAktarSecili1ActionPerformed);

        btnSagAktarSecili2.setText(">");
        btnSagAktarSecili2.addActionListener(this::btnSagAktarSecili2ActionPerformed);

        btnSagAktarSecili3.setText(">");
        btnSagAktarSecili3.addActionListener(this::btnSagAktarSecili3ActionPerformed);

        btnSagAktarSecili4.setText(">");
        btnSagAktarSecili4.addActionListener(this::btnSagAktarSecili4ActionPerformed);

        btnSagAktarSecili5.setText(">");
        btnSagAktarSecili5.addActionListener(this::btnSagAktarSecili5ActionPerformed);

        btnSolAktarSecili.setText("<");

        btnSolAktarHepsi.setText("<<");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnEkle)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSolAktarHepsi)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnSolAktarSecili, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnSagAktarHepsi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnSagAktarSecili1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnSagAktarSecili2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnSagAktarSecili3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnSagAktarSecili4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnSagAktarSecili5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(69, 69, 69))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(btnEkle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSagAktarHepsi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSagAktarSecili1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSagAktarSecili2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSagAktarSecili3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSagAktarSecili4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSagAktarSecili5))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                        .addComponent(jScrollPane1)))
                .addGap(18, 18, 18)
                .addComponent(btnSolAktarSecili)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSolAktarHepsi)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEkleActionPerformed
        // TODO add your handling code here:
        model1.clear();
        Random rnd = new Random();
        for (int i = 0; i < 10; i++) {
            int sayi = rnd.nextInt(100);//0-99
            model1.addElement(String.valueOf(sayi));
        }
    }//GEN-LAST:event_btnEkleActionPerformed

    private void btnSagAktarHepsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSagAktarHepsiActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < model1.size(); i++) {
            String siradakiEleman = model1.getElementAt(i);
            model2.addElement(siradakiEleman);
        }
        model1.clear();
    }//GEN-LAST:event_btnSagAktarHepsiActionPerformed

    private void btnSagAktarSecili1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSagAktarSecili1ActionPerformed
        // TODO add your handling code here:
        //secili elemanların Index değerini diziye ata
        int[] seciliIndexler=jList1.getSelectedIndices();
        //secili elemanların Index değeri kullanarak
        //model1 den model2 e ata
        for(int i = 0; i<seciliIndexler.length;i++){
            int siradakiIndex = seciliIndexler[i];
            String siradakiEleman = model1.elementAt(siradakiIndex);
            model2.addElement(siradakiEleman);
        }
        //secili elemanların Index değerini kullanıp
        //model1 den sondan başa doğru sil
        for(int i=seciliIndexler.length-1;i>=0;i--){
            int siradakiIndex = seciliIndexler[i];
            model1.removeElementAt(siradakiIndex);
        }
            
    }//GEN-LAST:event_btnSagAktarSecili1ActionPerformed

    private void btnSagAktarSecili2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSagAktarSecili2ActionPerformed
        // TODO add your handling code here:
        List<String> seciliElemanlar=jList1.getSelectedValuesList();
        for(int i=0;i<seciliElemanlar.size();i++){
            String siradakiEleman = seciliElemanlar.get(i);
            model2.addElement(siradakiEleman);
        }
    }//GEN-LAST:event_btnSagAktarSecili2ActionPerformed

    private void btnSagAktarSecili3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSagAktarSecili3ActionPerformed
        // TODO add your handling code here:
        for(int i=0;i<jList1.getSelectedValuesList().size();i++){
            String siradakiEleman = jList1.getSelectedValuesList().get(i);
            model2.addElement(siradakiEleman);
        }
    }//GEN-LAST:event_btnSagAktarSecili3ActionPerformed

    private void btnSagAktarSecili4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSagAktarSecili4ActionPerformed
        // TODO add your handling code here:
        
        //secili elemanların Index değeri kullanarak
        //model1 den model2 e ata
        for(int i = 0; i<jList1.getSelectedIndices().length;i++){
            int siradakiIndex = jList1.getSelectedIndices()[i];
            String siradakiEleman = model1.elementAt(siradakiIndex);
            model2.addElement(siradakiEleman);
        }
    }//GEN-LAST:event_btnSagAktarSecili4ActionPerformed

    private void btnSagAktarSecili5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSagAktarSecili5ActionPerformed
        // TODO add your handling code here:
         do{
            int siradakiIndex = jList1.getSelectedIndices()[0];
            model2.addElement(model1.getElementAt(siradakiIndex));
            model1.removeElementAt(siradakiIndex);
        }while(jList1.getSelectedIndices().length>0);
    }//GEN-LAST:event_btnSagAktarSecili5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new NewJFrame1().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEkle;
    private javax.swing.JButton btnSagAktarHepsi;
    private javax.swing.JButton btnSagAktarSecili1;
    private javax.swing.JButton btnSagAktarSecili2;
    private javax.swing.JButton btnSagAktarSecili3;
    private javax.swing.JButton btnSagAktarSecili4;
    private javax.swing.JButton btnSagAktarSecili5;
    private javax.swing.JButton btnSolAktarHepsi;
    private javax.swing.JButton btnSolAktarSecili;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
