/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.vizesonrasi_2;

/**
 *
 * @author TA
 */
public class ToplamaForm extends javax.swing.JFrame {
    
    private javax.swing.JLabel lblSayi1;
    private javax.swing.JLabel lblSayi2;
    private javax.swing.JLabel lblSonuc;
    private javax.swing.JTextField txtSayi1;
    private javax.swing.JTextField txtSayi2;
    private javax.swing.JButton btnTopla;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ToplamaForm.class.getName());

    /**
     * Creates new form ToplamaForm
     */
    public ToplamaForm() {
        initComponents();
        componentOlustur();
    }
    
    private void componentOlustur() {

        setLayout(null); // ABSOLUTE LAYOUT

        lblSayi1 = new javax.swing.JLabel("1. Sayı:");
        lblSayi1 = new javax.swing.JLabel();
        //lblSayi1.setText("1. Sayı:");
        lblSayi2 = new javax.swing.JLabel("2. Sayı:");
        lblSonuc = new javax.swing.JLabel("Sonuç:");

        txtSayi1 = new javax.swing.JTextField();
        txtSayi2 = new javax.swing.JTextField();

        btnTopla = new javax.swing.JButton("Topla");

        // SABİT PİKSEL YERLEŞİM (PROBLEM BURADA BAŞLIYOR)
        lblSayi1.setBounds(30, 30, 80, 25);
        txtSayi1.setBounds(120, 30, 100, 25);

        lblSayi2.setBounds(30, 70, 80, 25);
        txtSayi2.setBounds(120, 70, 100, 25);

        btnTopla.setBounds(120, 110, 100, 30);

        lblSonuc.setBounds(30, 160, 200, 25);

        add(lblSayi1);
        add(txtSayi1);
        add(lblSayi2);
        add(txtSayi2);
        add(btnTopla);
        add(lblSonuc);

        setSize(400, 300);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ToplamaForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
